### ISSUE TITLE
Alternative License

### ISSUE THREAD

**Issue by doubleday** [timblechmann/nova-simd#4]
Hi

I experimented with nova-simd the last couple of days. Great stuff really!

Problem is: one of my main targets would be iOS. The GPL prohibits this. I assume that you want to prevent the use of your work in commercial software. But maybe you would also consider another / additional licensing scheme.

**Comment by timblechmann** [comment]
hi. yes: it is GPL, so it cannot be used with code, which is not GPL-compatible, and i'm not planning to release it under a more permissive license, as it took me a significant amount of time to develop the library.

but if you find it useful for your project, i'd be more than happy to re-license it for you under a commercial license. maybe we can discuss this via email (tim@klingt.org)?

btw, another interesting simd library is boost.simd/nt2: https://github.com/jfalcou/boost.simd. it is bsl-licensed, but arm-support requires a commercial license as well.
